"""
Comprehensive clinical database for 22+ multi-specialty verified and demo doctors.
"""

DOCTORS_DATA = [
    # --- CARDIOLOGY ---
    {
        "name": "Dr. Vikram Sharma",
        "email": "dr.vikram@clinic.com",
        "specialisation": "Cardiology",
        "qualifications": "MBBS, MD (General Medicine), DM (Cardiology), FACC",
        "experience_years": 16,
        "hospital_name": "Apollo Hospitals, Jubilee Hills",
        "location": "Hyderabad",
        "consultation_fee": 1200,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Hindi, Telugu",
        "working_start": "09:00",
        "working_end": "14:00",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 20,
        "rating": 4.9,
        "review_count": 164,
        "verification_status": "Verified Specialist",
        "bio": "Senior Consultant Interventional Cardiologist with over 16 years of expertise in complex coronary angioplasty, transcatheter aortic valve implantation (TAVI), heart failure management, and preventive cardiovascular care.",
        "expertise": "Coronary Angioplasty, Heart Failure, Hypertension, Echocardiography, TAVI, Cardiac Rehabilitation",
        "research_interests": "Novel Drug-Eluting Stents, Early Biomarkers in Acute Coronary Syndrome",
        "publications": "32 peer-reviewed articles published in the Journal of the American College of Cardiology (JACC) and Indian Heart Journal.",
        "source_url": "https://sahayakhealth.org/specialists/cardiology/dr-vikram-sharma",
    },
    {
        "name": "Dr. Priya Sundaram",
        "email": "dr.priya.cardio@clinic.com",
        "specialisation": "Cardiology",
        "qualifications": "MBBS, MD (Medicine), DM (Cardiology), FSCAI",
        "experience_years": 12,
        "hospital_name": "Fortis Hospital, Cunningham Road",
        "location": "Bengaluru",
        "consultation_fee": 1100,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Tamil, Kannada, Hindi",
        "working_start": "10:00",
        "working_end": "16:00",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 20,
        "rating": 4.8,
        "review_count": 142,
        "verification_status": "Verified Specialist",
        "bio": "Expert Clinical Cardiologist specializing in preventive cardiology, coronary artery disease management, arrhythmia detection, and non-invasive cardiac imaging.",
        "expertise": "Preventive Cardiology, Arrhythmia, Lipid Management, 2D/3D Echo, Holter Monitoring",
        "research_interests": "Early Cardiovascular Disease Risk Modeling in Young Adults",
        "publications": "18 publications in Circulation and Indian Heart Journal.",
        "source_url": "https://sahayakhealth.org/specialists/cardiology/dr-priya-sundaram",
    },

    # --- ONCOLOGY (Multiple Specialists) ---
    {
        "name": "Dr. Sanjay Deshmukh",
        "email": "dr.sanjay@clinic.com",
        "specialisation": "Oncology",
        "qualifications": "MBBS, MD (Medicine), DM (Medical Oncology), ESMO Certified",
        "experience_years": 20,
        "hospital_name": "Tata Memorial Centre Affiliate, Parel",
        "location": "Mumbai",
        "consultation_fee": 1500,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Hindi, Marathi",
        "working_start": "11:00",
        "working_end": "17:00",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 30,
        "rating": 4.9,
        "review_count": 190,
        "verification_status": "Verified Specialist",
        "bio": "Leading Medical Oncologist specializing in targeted immunotherapy, precision oncology, breast cancer, lung cancer therapeutics, and gastrointestinal malignancies.",
        "expertise": "Targeted Immunotherapy, Chemotherapy Protocols, Breast Cancer, GI Malignancies, Genomic Oncology Testing",
        "research_interests": "Molecular Biomarkers in Immunotherapy Resistance, Liquid Biopsies for Early Detection",
        "publications": "50+ peer-reviewed papers in Lancet Oncology, Annals of Oncology, and Indian Journal of Cancer.",
        "source_url": "https://sahayakhealth.org/specialists/oncology/dr-sanjay-deshmukh",
    },
    {
        "name": "Dr. Radhika Madan",
        "email": "dr.radhika.onco@clinic.com",
        "specialisation": "Oncology",
        "qualifications": "MBBS, MS (General Surgery), M.Ch (Surgical Oncology)",
        "experience_years": 16,
        "hospital_name": "Max Super Speciality Hospital, Vaishali",
        "location": "Delhi",
        "consultation_fee": 1400,
        "consultation_mode": "In-Clinic",
        "languages": "English, Hindi, Punjabi",
        "working_start": "09:30",
        "working_end": "15:30",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 25,
        "rating": 4.9,
        "review_count": 152,
        "verification_status": "Verified Specialist",
        "bio": "Consultant Surgical Oncologist with special interest in breast conservation surgery, robotic oncologic resections, gynecological cancers, and soft tissue sarcomas.",
        "expertise": "Breast Oncoplastic Surgery, Minimally Invasive Cancer Surgery, Thyroid Oncology, Head & Neck Tumors",
        "research_interests": "Sentinel Lymph Node Biopsy in Early-Stage Breast Cancer, Organ Preservation Protocols",
        "publications": "28 publications in the World Journal of Surgical Oncology.",
        "source_url": "https://sahayakhealth.org/specialists/oncology/dr-radhika-madan",
    },
    {
        "name": "Dr. Vikramaditya Reddy",
        "email": "dr.vikramaditya.onco@clinic.com",
        "specialisation": "Oncology",
        "qualifications": "MBBS, MD (Radiotherapy), DNB (Radiation Oncology), FASTRO",
        "experience_years": 14,
        "hospital_name": "Basavatarakam Indo-American Cancer Hospital",
        "location": "Hyderabad",
        "consultation_fee": 1300,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Telugu, Hindi",
        "working_start": "10:00",
        "working_end": "16:00",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 20,
        "rating": 4.8,
        "review_count": 135,
        "verification_status": "Verified Specialist",
        "bio": "Senior Radiation Oncologist specializing in stereotactic body radiation therapy (SBRT), proton beam planning, IGRT/IMRT, and central nervous system tumors.",
        "expertise": "Stereotactic Radiotherapy (SBRT/SRS), IMRT/IGRT, Brain Tumors, Prostate Cancer Radiation",
        "research_interests": "AI-Driven Radiation Contouring and Dose Fractionation Optimization",
        "publications": "22 papers in the International Journal of Radiation Oncology.",
        "source_url": "https://sahayakhealth.org/specialists/oncology/dr-vikramaditya-reddy",
    },

    # --- NEUROLOGY ---
    {
        "name": "Dr. Ananya Sen",
        "email": "dr.ananya@clinic.com",
        "specialisation": "Neurology",
        "qualifications": "MBBS, MD (Medicine), DM (Neurology), FAAN",
        "experience_years": 14,
        "hospital_name": "Max Super Speciality Hospital, Saket",
        "location": "Delhi",
        "consultation_fee": 1400,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Hindi, Bengali",
        "working_start": "10:00",
        "working_end": "16:00",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 20,
        "rating": 4.9,
        "review_count": 138,
        "verification_status": "Verified Specialist",
        "bio": "Consultant Neurologist specializing in neurovascular disorders, stroke rehabilitation, Parkinson's disease, epilepsy management, and advanced neuro-critical care.",
        "expertise": "Acute Stroke Intervention, Epilepsy, Parkinson's Disease, Migraine & Chronic Headache, Neuropathy",
        "research_interests": "Neuroplasticity in Post-Stroke Recovery, Deep Brain Stimulation Protocols",
        "publications": "24 clinical papers in the Annals of Indian Academy of Neurology and Neurology India.",
        "source_url": "https://sahayakhealth.org/specialists/neurology/dr-ananya-sen",
    },

    # --- ORTHOPEDICS ---
    {
        "name": "Dr. Rajesh Varma",
        "email": "dr.rajesh@clinic.com",
        "specialisation": "Orthopedics",
        "qualifications": "MBBS, MS (Orthopedics), M.Ch (Joint Replacement)",
        "experience_years": 18,
        "hospital_name": "Fortis Hospital, Bannerghatta Road",
        "location": "Bengaluru",
        "consultation_fee": 1000,
        "consultation_mode": "In-Clinic",
        "languages": "English, Kannada, Hindi",
        "working_start": "09:30",
        "working_end": "15:30",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 20,
        "rating": 4.8,
        "review_count": 210,
        "verification_status": "Verified Specialist",
        "bio": "Chief Orthopedic and Joint Replacement Surgeon with extensive experience in robotic total knee & hip replacement, complex trauma surgery, and arthroscopic sports injury treatments.",
        "expertise": "Robotic Knee Replacement, Hip Arthroplasty, ACL Reconstruction, Rotator Cuff Repair, Osteoarthritis Care",
        "research_interests": "Minimally Invasive Joint Replacement Techniques, Biomimetic Cartilage Scaffolds",
        "publications": "40+ publications in the Journal of Bone and Joint Surgery and Indian Journal of Orthopaedics.",
        "source_url": "https://sahayakhealth.org/specialists/orthopedics/dr-rajesh-varma",
    },

    # --- DERMATOLOGY ---
    {
        "name": "Dr. Karan Mehta",
        "email": "dr.karan@clinic.com",
        "specialisation": "Dermatology",
        "qualifications": "MBBS, MD (Dermatology, Venereology & Leprosy)",
        "experience_years": 11,
        "hospital_name": "Manipal Hospital, Kharadi",
        "location": "Mumbai",
        "consultation_fee": 800,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Hindi, Marathi, Gujarati",
        "working_start": "14:00",
        "working_end": "18:00",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 15,
        "rating": 4.8,
        "review_count": 185,
        "verification_status": "Verified Specialist",
        "bio": "Specialist Dermatologist and Aesthetic Consultant focusing on chronic eczema, psoriasis management, acne scar revisions, laser dermatology, and trichology.",
        "expertise": "Acne & Scar Management, Psoriasis, Eczema, Anti-Aging Therapies, Hair Restoration, Laser Treatments",
        "research_interests": "Biologic Therapies for Severe Psoriasis, Advanced Laser Phototherapy",
        "publications": "18 research papers in Indian Journal of Dermatology and Clinical Dermatology.",
        "source_url": "https://sahayakhealth.org/specialists/dermatology/dr-karan-mehta",
    },

    # --- PEDIATRICS ---
    {
        "name": "Dr. Pooja Kulkarni",
        "email": "dr.pooja@clinic.com",
        "specialisation": "Pediatrics",
        "qualifications": "MBBS, MD (Pediatrics), DNB, Fellowship in Neonatology",
        "experience_years": 12,
        "hospital_name": "Rainbow Children's Hospital, Banjara Hills",
        "location": "Hyderabad",
        "consultation_fee": 750,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Hindi, Telugu, Marathi",
        "working_start": "09:00",
        "working_end": "13:30",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 15,
        "rating": 4.9,
        "review_count": 224,
        "verification_status": "Verified Specialist",
        "bio": "Compassionate Pediatrician and Neonatologist dedicated to infant growth monitoring, childhood immunization, pediatric allergy care, and developmental milestone assessments.",
        "expertise": "Newborn Care, Pediatric Nutrition, Asthma in Children, Vaccination, Adolescent Health, Developmental Delay",
        "research_interests": "Early Childhood Nutrition and Gut Microbiome Development",
        "publications": "15 publications in Indian Pediatrics and International Journal of Contemporary Pediatrics.",
        "source_url": "https://sahayakhealth.org/specialists/pediatrics/dr-pooja-kulkarni",
    },

    # --- GYNECOLOGY ---
    {
        "name": "Dr. Meera Nambiar",
        "email": "dr.meera@clinic.com",
        "specialisation": "Gynecology & Obstetrics",
        "qualifications": "MBBS, MS (Obstetrics & Gynecology), DGO, FICOG",
        "experience_years": 15,
        "hospital_name": "Cloudnine Hospital, T Nagar",
        "location": "Chennai",
        "consultation_fee": 900,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Tamil, Malayalam, Hindi",
        "working_start": "10:00",
        "working_end": "15:00",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 20,
        "rating": 4.9,
        "review_count": 195,
        "verification_status": "Verified Specialist",
        "bio": "Senior Gynecologist and Laparoscopic Surgeon specializing in high-risk pregnancy care, PCOS management, minimally invasive hysterectomy, and fertility preservation.",
        "expertise": "High-Risk Pregnancy, Laparoscopic Gynaec Surgery, PCOS/PCOD, Menopause Management, Infertility Workup",
        "research_interests": "Gestational Diabetes Prevention, Advanced Endometriosis Management",
        "publications": "22 clinical studies in the Journal of Obstetrics and Gynaecology of India.",
        "source_url": "https://sahayakhealth.org/specialists/gynecology/dr-meera-nambiar",
    },

    # --- PSYCHIATRY ---
    {
        "name": "Dr. Rohan Kapoor",
        "email": "dr.rohan@clinic.com",
        "specialisation": "Psychiatry",
        "qualifications": "MBBS, MD (Psychiatry), MRCPsych (UK)",
        "experience_years": 10,
        "hospital_name": "MindCare Clinic, Indiranagar",
        "location": "Bengaluru",
        "consultation_fee": 1100,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Hindi, Kannada, Punjabi",
        "working_start": "13:00",
        "working_end": "19:00",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 30,
        "rating": 4.9,
        "review_count": 145,
        "verification_status": "Verified Specialist",
        "bio": "Holistic Neuropsychiatrist offering evidence-based treatments for anxiety disorders, major depressive disorder, adult ADHD, bipolar spectrum, and cognitive behavioral wellness.",
        "expertise": "Anxiety & Panic Disorders, Clinical Depression, Adult ADHD, Insomnia Therapy, Stress & Burnout Management",
        "research_interests": "Digital Therapeutics in Mental Health, Pharmacogenomics of Antidepressant Response",
        "publications": "14 articles in the Indian Journal of Psychiatry and British Journal of Psychiatry.",
        "source_url": "https://sahayakhealth.org/specialists/psychiatry/dr-rohan-kapoor",
    },

    # --- GASTROENTEROLOGY ---
    {
        "name": "Dr. Alok Trivedi",
        "email": "dr.alok@clinic.com",
        "specialisation": "Gastroenterology",
        "qualifications": "MBBS, MD (Medicine), DM (Gastroenterology), FACG",
        "experience_years": 17,
        "hospital_name": "Medanta The Medicity, Sector 38",
        "location": "Delhi",
        "consultation_fee": 1300,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Hindi",
        "working_start": "09:00",
        "working_end": "14:30",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 20,
        "rating": 4.8,
        "review_count": 178,
        "verification_status": "Verified Specialist",
        "bio": "Senior Consultant Gastroenterologist & Hepatologist with deep specialization in inflammatory bowel disease (IBD), fatty liver disease, therapeutic endoscopy, and pancreaticobiliary interventions.",
        "expertise": "Endoscopy, Colonoscopy, Acid Reflux/GERD, Fatty Liver (NASH), Crohn's & Colitis, ERCP",
        "research_interests": "Gut-Liver Axis in Metabolic Liver Disease, Advanced Therapeutic Endoscopy",
        "publications": "28 publications in the American Journal of Gastroenterology and Tropical Gastroenterology.",
        "source_url": "https://sahayakhealth.org/specialists/gastroenterology/dr-alok-trivedi",
    },

    # --- PULMONOLOGY ---
    {
        "name": "Dr. Sunita Banerjee",
        "email": "dr.sunita@clinic.com",
        "specialisation": "Pulmonology",
        "qualifications": "MBBS, MD (Pulmonary Medicine), FCCP (USA), FICS",
        "experience_years": 13,
        "hospital_name": "Woodlands Multispeciality Hospital, Alipore",
        "location": "Kolkata",
        "consultation_fee": 950,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Bengali, Hindi",
        "working_start": "10:30",
        "working_end": "16:30",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 20,
        "rating": 4.8,
        "review_count": 132,
        "verification_status": "Verified Specialist",
        "bio": "Distinguished Pulmonologist and Sleep Medicine Specialist focusing on severe asthma, chronic obstructive pulmonary disease (COPD), post-COVID lung recovery, and sleep apnea.",
        "expertise": "Asthma Management, COPD Rehabilitation, Sleep Apnea (Polysomnography), Interstitial Lung Disease, Bronchoscopy",
        "research_interests": "Pollution-Induced Airway Inflammation, Home Non-Invasive Ventilation Efficacy",
        "publications": "19 research papers in Lung India and European Respiratory Journal Open.",
        "source_url": "https://sahayakhealth.org/specialists/pulmonology/dr-sunita-banerjee",
    },

    # --- GENERAL MEDICINE ---
    {
        "name": "Dr. Asha Rao",
        "email": "dr.asha@clinic.com",
        "specialisation": "General Medicine",
        "qualifications": "MBBS, MD (Internal Medicine)",
        "experience_years": 15,
        "hospital_name": "Manipal Clinic, Koramangala",
        "location": "Bengaluru",
        "consultation_fee": 600,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Kannada, Hindi, Telugu",
        "working_start": "09:00",
        "working_end": "13:00",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 20,
        "rating": 4.8,
        "review_count": 240,
        "verification_status": "Verified Specialist",
        "bio": "Experienced General Physician dedicated to comprehensive chronic disease management, diabetes mellitus, infectious disease therapeutics, preventive health screenings, and geriatric medicine.",
        "expertise": "Diabetes Care, Hypertension, Infectious Diseases, Thyroid Disorders, Preventive Health Checks",
        "research_interests": "Preventive Community Medicine and Early Lifestyle Interventions for Metabolic Syndrome",
        "publications": "12 clinical papers in Journal of Association of Physicians of India (JAPI).",
        "source_url": "https://sahayakhealth.org/specialists/general-medicine/dr-asha-rao",
    },

    # --- ENDOCRINOLOGY ---
    {
        "name": "Dr. Harish Patel",
        "email": "dr.harish@clinic.com",
        "specialisation": "Endocrinology",
        "qualifications": "MBBS, MD (Internal Medicine), DM (Endocrinology), FACE",
        "experience_years": 14,
        "hospital_name": "Sterling Hospitals, Memnagar",
        "location": "Ahmedabad",
        "consultation_fee": 1100,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Gujarati, Hindi",
        "working_start": "09:00",
        "working_end": "14:00",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 20,
        "rating": 4.9,
        "review_count": 156,
        "verification_status": "Verified Specialist",
        "bio": "Renowned Endocrinologist and Diabetologist providing cutting-edge management of type 1 and type 2 diabetes, thyroid nodules, adrenal disorders, osteoporosis, and pituitary dysfunctions.",
        "expertise": "Complex Diabetes & Insulin Pumps, Thyroid Disorders, Osteoporosis, Pituitary & Adrenal Care, Metabolic Obesity",
        "research_interests": "Continuous Glucose Monitoring (CGM) Protocols, SGLT-2 Inhibitor Renal Protection",
        "publications": "21 publications in Indian Journal of Endocrinology and Metabolism and Diabetes Care.",
        "source_url": "https://sahayakhealth.org/specialists/endocrinology/dr-harish-patel",
    },

    # --- OPHTHALMOLOGY ---
    {
        "name": "Dr. Divya Rangarajan",
        "email": "dr.divya@clinic.com",
        "specialisation": "Ophthalmology",
        "qualifications": "MBBS, MS (Ophthalmology), FICO (UK), Fellowship in Cornea",
        "experience_years": 12,
        "hospital_name": "Sankara Eye Hospital, Kundalahalli",
        "location": "Bengaluru",
        "consultation_fee": 850,
        "consultation_mode": "In-Clinic",
        "languages": "English, Tamil, Kannada, Hindi",
        "working_start": "09:30",
        "working_end": "15:30",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 15,
        "rating": 4.9,
        "review_count": 172,
        "verification_status": "Verified Specialist",
        "bio": "Senior Cornea and Refractive Cataract Surgeon specializing in laser vision correction (LASIK/SMILE), dry eye syndrome therapies, corneal transplants, and pediatric refractive errors.",
        "expertise": "Cataract Surgery (Phacoemulsification), LASIK & Refractive Correction, Cornea Transplants, Glaucoma Screening, Dry Eye Care",
        "research_interests": "Femtosecond Laser Assisted Cataract Surgery, Corneal Collagen Cross-Linking",
        "publications": "17 papers in the Indian Journal of Ophthalmology and British Journal of Ophthalmology.",
        "source_url": "https://sahayakhealth.org/specialists/ophthalmology/dr-divya-rangarajan",
    },

    # --- ENT ---
    {
        "name": "Dr. Pradeep Iyer",
        "email": "dr.pradeep@clinic.com",
        "specialisation": "ENT (Otolaryngology)",
        "qualifications": "MBBS, MS (ENT), DOHNS (Royal College of Surgeons, UK)",
        "experience_years": 13,
        "hospital_name": "Aster CMI Hospital, Sahakara Nagar",
        "location": "Bengaluru",
        "consultation_fee": 800,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Kannada, Hindi, Malayalam",
        "working_start": "11:00",
        "working_end": "17:00",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 15,
        "rating": 4.8,
        "review_count": 140,
        "verification_status": "Verified Specialist",
        "bio": "Consultant ENT, Head & Neck Surgeon with high surgical acumen in functional endoscopic sinus surgery (FESS), hearing restoration, vertigo clinic, and vocal cord micro-surgeries.",
        "expertise": "Sinusitis & FESS, Tinnitus & Hearing Loss, Vertigo / BPPV, Snoring & Sleep Apnea Surgery, Pediatric ENT Care",
        "research_interests": "Endoscopic Skull Base Approaches, High-Resolution Auditory Evoked Potentials",
        "publications": "16 clinical articles in Indian Journal of Otolaryngology and Head & Neck Surgery.",
        "source_url": "https://sahayakhealth.org/specialists/ent/dr-pradeep-iyer",
    },

    # --- UROLOGY ---
    {
        "name": "Dr. Tarun Saxena",
        "email": "dr.tarun@clinic.com",
        "specialisation": "Urology",
        "qualifications": "MBBS, MS (Surgery), M.Ch (Urology), DNB",
        "experience_years": 16,
        "hospital_name": "Kokilaben Dhirubhai Ambani Hospital, Andheri",
        "location": "Mumbai",
        "consultation_fee": 1400,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Hindi, Marathi",
        "working_start": "09:00",
        "working_end": "14:00",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 20,
        "rating": 4.9,
        "review_count": 182,
        "verification_status": "Verified Specialist",
        "bio": "Senior Consultant Urologist & Andrologist performing laser kidney stone surgeries (RIRS/PCNL), robotic prostatectomy, male infertility management, and reconstructive urology.",
        "expertise": "Laser Kidney Stone Surgery (RIRS), Prostate Enlargement (BPH), Urological Oncology, Urinary Incontinence, Men's Health",
        "research_interests": "Thulium Fiber Laser Lithotripsy, Minimally Invasive Robotic Prostatectomies",
        "publications": "31 publications in the Indian Journal of Urology and Journal of Endourology.",
        "source_url": "https://sahayakhealth.org/specialists/urology/dr-tarun-saxena",
    },

    # --- RHEUMATOLOGY ---
    {
        "name": "Dr. Kavita Nair",
        "email": "dr.kavita@clinic.com",
        "specialisation": "Rheumatology",
        "qualifications": "MBBS, MD (Medicine), DNB (Rheumatology), FACR",
        "experience_years": 11,
        "hospital_name": "Amrita Institute of Medical Sciences, Edappally",
        "location": "Chennai",
        "consultation_fee": 900,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Malayalam, Tamil, Hindi",
        "working_start": "10:00",
        "working_end": "16:00",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 20,
        "rating": 4.8,
        "review_count": 118,
        "verification_status": "Verified Specialist",
        "bio": "Expert Rheumatologist providing holistic multidisciplinary management of rheumatoid arthritis, lupus (SLE), ankylosing spondylitis, gout, and systemic vasculitis.",
        "expertise": "Rheumatoid Arthritis, Systemic Lupus Erythematosus (SLE), Ankylosing Spondylitis, Fibromyalgia, Joint Injections",
        "research_interests": "Early Biologic Intervention in Spondyloarthropathies, Autoantibody Profiles in Lupus",
        "publications": "14 papers in Indian Journal of Rheumatology and Arthritis Care & Research.",
        "source_url": "https://sahayakhealth.org/specialists/rheumatology/dr-kavita-nair",
    },

    # --- NEPHROLOGY ---
    {
        "name": "Dr. Arvind Singhal",
        "email": "dr.arvind@clinic.com",
        "specialisation": "Nephrology",
        "qualifications": "MBBS, MD (Medicine), DM (Nephrology), FASN",
        "experience_years": 19,
        "hospital_name": "BLK-Max Super Speciality Hospital, Pusa Road",
        "location": "Delhi",
        "consultation_fee": 1350,
        "consultation_mode": "Online & In-Clinic",
        "languages": "English, Hindi, Punjabi",
        "working_start": "09:00",
        "working_end": "15:00",
        "working_days": "0,1,2,3,4",
        "slot_duration_minutes": 20,
        "rating": 4.9,
        "review_count": 194,
        "verification_status": "Verified Specialist",
        "bio": "Director and Senior Consultant Nephrologist specializing in chronic kidney disease (CKD) staging, hemodialysis protocols, renal transplantation care, and diabetic nephropathy.",
        "expertise": "Kidney Transplantation, Chronic Kidney Disease (CKD), Dialysis Management, Glomerulonephritis, Hypertension & Renal Care",
        "research_interests": "Immunosuppression Protocols in Renal Transplants, Slowing Progression of Diabetic Nephropathy",
        "publications": "38 papers in Indian Journal of Nephrology and Kidney International Reports.",
        "source_url": "https://sahayakhealth.org/specialists/nephrology/dr-arvind-singhal",
    },

    # --- PLASTIC SURGERY ---
    {
        "name": "Dr. Neha Agarwal",
        "email": "dr.neha@clinic.com",
        "specialisation": "Plastic & Reconstructive Surgery",
        "qualifications": "MBBS, MS (General Surgery), M.Ch (Plastic & Reconstructive Surgery)",
        "experience_years": 13,
        "hospital_name": "Sir Ganga Ram Hospital, Rajinder Nagar",
        "location": "Delhi",
        "consultation_fee": 1500,
        "consultation_mode": "In-Clinic",
        "languages": "English, Hindi",
        "working_start": "11:00",
        "working_end": "17:00",
        "working_days": "0,1,2,3,4,5",
        "slot_duration_minutes": 30,
        "rating": 4.9,
        "review_count": 165,
        "verification_status": "Verified Specialist",
        "bio": "Senior Consultant Plastic & Cosmetic Surgeon with specialized training in microvascular reconstructive surgery, burn wound recovery, trauma reconstructions, and aesthetic facial reshaping.",
        "expertise": "Reconstructive Microsurgery, Burn Management, Facial Aesthetic Surgery, Scar Revision, Hand Surgery, Body Contouring",
        "research_interests": "Perforator Flap Microvascular Reconstruction, Advanced Tissue Engineering in Scar Remodeling",
        "publications": "20 publications in Indian Journal of Plastic Surgery and Aesthetic Plastic Surgery.",
        "source_url": "https://sahayakhealth.org/specialists/plastic-surgery/dr-neha-agarwal",
    },
]
